# .swiftlint.yml
# Basic configuration, enable recommended rules
opt_in_rules:
  - empty_count
  - explicit_init
  - explicit_type_interface
  - first_where
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - trailing_whitespace # Often handled by SwiftFormat

# Exclude vendor directories and build artifacts
excluded:
  - .build
  - vendor
# You can customize rules further here, e.g.:
# line_length: 140
# identifier_name:
#   min_length: # only warning
#     warning: 3
#   excluded: # excluded via string array
#     - id
#     - URL
#     - GlobalAPIKey
